### ISSUE TITLE
Request for preservation of mtime during file delivery

### ISSUE THREAD

**Issue by jmdrake1959** [avpreserve/uk-exactly#2]

**Comment by bertramlyons** [comment]
This request has come in from Emory University, and NCSU, as well. Options include investigating zip implementation to preserve the access/creation/modification times for files before zipping; implement another packager, such as tar, that will preserve these times before serializing; or extract text doc of original a/c/m dates on original file system before packing for delivery - this text doc would be included in final package.

**Comment by bertramlyons** [comment]
Current version of Exactly extracts file system information from original source and stores the data as a separate text file (FileSystemInfo.txt) that is added to the bag. Because not all file systems allow the preservation of timestamps during transfer, this allows that data to be captured from original source and preserved alongside the file(s) during delivery.
